### ISSUE TITLE
Initialize Django project

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#10]
Pretty straightforward, using **django-admin** start a new project (taking care to use the root directory as the project directory) and start a new app, this app will be our API.

It'll be also necessary to update the `.travis.yml` config file adding a few more settings:

- Enable a database service
- Set Django environment variables
- Execute Django database migration
- Execute Django test runner
- Set Black command pointing to the app folder

**Comment by ericrommel** [comment]
Initialize Django project:
- [OK] django-admin startproject loan_site

- [OK] python manage.py startapp loan_api

Update the .travis.yml config file:

- [OK] Enable a database service

- [OK] Set Django environment variables

- [OK] Execute Django database migration

- [OK] Execute Django test runner

- [OK] Set Black command pointing to the app folder

**Comment by julianolf** [comment]
@ericrommel 

> * [OK] django-admin startproject loan_site
> * [OK] python manage.py startapp loan_api

For the directories names, if I would create them, I would probably use the names: **project** and **api**, just because the root directory already have the name of the project. But it is just a matter of preference.

**Comment by ericrommel** [comment]
That's okay, I will apply these changes.

**Comment by ericrommel** [comment]
Travis still failing.
https://travis-ci.com/ericrommel/loan-management-system/builds/109679458?utm_medium=notification&utm_source=email
