### ISSUE TITLE
Choose API documentation tool 

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#23]
There are plenty of options to generate API documentation for Django REST framework, from the [list](https://www.django-rest-framework.org/topics/documenting-your-api/) in the official site I would choose one of these:

- The **built-in** tool
- **drf-yasg** (Swagger or ReDoc)
- **Django REST** Swagger (Swagger)

I would like to hear from you guys which one do you prefer? We need to pick one so I think it would be better to do it in a democratic way by voting.

**Comment by julianolf** [comment]
My vote goes to **drf-yasg** that seems to be simple to configure and supports both Swagger and redoc.

**Comment by fhpimenta** [comment]
I also vote on **drf-yasg**, since it provides the documentation in several formats, besides doing everything in a simpler way.

**Comment by julianolf** [comment]
In our last call @caioCT said he agrees with @fhpimenta and me about using **drf-yasg** as the documentation tool for the API.
