### ISSUE TITLE
Adjust Loan model

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#27]
There are a few adjustments to be done for the **Loan** model in `api/models.py`.

- [x] Remove redundant/not necessary doc strings.
- [x] The field **amount** must be of type _FloatField_ not _IntegerField_.
- [x] The **installment** formula is incorrect, the constant _12_ must be the value of the **term**.
- [x] Add a new method called **balance** that calculates the loan balance for a given date, the parameter date shall have a default value as the current date and time.
- [x] Add annotation for the output of the methods.
- [x] Generate migration (depend on issue #26 to be done first).

**Comment by ericrommel** [comment]
@julianolf , I didn't understand it "The installment formula is incorrect, the constant 12 must be the value of the term." The term comes from json then, it is not a constant.

**Comment by julianolf** [comment]
Take a look [here](https://github.com/squad-4/loan-management-system/blob/e21576a4b15d2f7671f4171574b879450c02c587/api/models.py#L26), see how the rate is being calculated?

```python
r = self.rate / 12
```

There's a **12** hardcoded there.

What I mean is that such constant doesn't exist, it was supposed to be the value in the attribute **term**.

```python
r = self.rate / self.term
```
