### ISSUE TITLE
Adjust Payment model

### ISSUE THREAD

**Issue by julianolf** [squad-4/loan-management-system#28]
There are a few adjustments to be done for the **Payment** model in `api/models.py`.

- [x] Remove redundant/not necessary doc strings.
- [x] Change **on_delete** action of field **loan** to **CASCADE**.
- [x] Change **max_length** of field **payment** to **6**.
- [x] Change the output of the method **_ _ str _ _** to return the **Payment** ID instead of the **Loan**.
- [x] Add annotation for the output of the method.
- [x] Generate migration (depend on issue #26 to be done first).

**Comment by caioCT** [comment]
HI @julianolf,
I'm not sure about what the task "Add annotation for the output of the method" means.
Would you mind defining this task a little more precisely?

**Comment by julianolf** [comment]
@caioCT sure!

In Python we can add special annotations to define for example the type of an input or output data, even if the language is not static typed. It works like a hint telling that some value should be of some specific type.

Let me show an example:

```python
# common python function declaration

def add(a, b = 1):
    return a + b
```

```python
# same python function declaration with type hints

def add(a: int, b: int = 1) -> int:
    return a + b
```

So what I mean is that all methods (if we are going to use annotations for type hinting) should have both declared, parameters and output. Like `def __str__(self) -> str:` and so on.

I hope this can help you, if it's still not clear let me know.

PS.: If you want to know more about this subject take a look [here](https://docs.python.org/3/library/typing.html) and [here](https://www.python.org/dev/peps/pep-0484/).

**Comment by caioCT** [comment]
Ohh, I thought you were talking about Django queryset annotations.
Thanks!
